class TagNotFoundError(Exception): ...


class TagAlreadyExistsError(Exception): ...


class BookmarkNotFoundError(Exception): ...


class BookmarkAlreadyExistsError(Exception): ...


class ResourceAlreadyExistsError(Exception): ...


class ResourceNotFoundError(Exception): ...


class ResourceValidationError(Exception): ...


class TrashedResourceNotFoundError(Exception): ...


class ConversionError(Exception): ...


class ConversionNotNeededError(Exception): ...


class ImportPathError(Exception): ...
